galeria/urls.py
from django.urls import path
from galeria.views import index, imagem, buscar

app_name = 'galeria'


urlpatterns = [
    path('', index, name='index.html'),
    path('imagem/<int:foto_id>', imagem, name='imagem.html'),
    path("buscar", buscar, name="buscar"),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('galeria.urls')),
    path('usuarios/', include("usuarios.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from usuarios.views import login, cadastro, buscar

app_name = 'usuarios'

urlpatterns = [
    path('login', login, name='login'),
    path('cadastro', cadastro, name='cadastro'),
        path('buscar', buscar, name='buscar'),

]

galeria/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Fotografia(models.Model):

    OPCOES_CATEGORIA = [
        ("NEBULOSA", "Nebulosa"),
        ("ESTRELA", "Estrela"),
        ("GALAXIA", "Galaxia"),
        ("PLANETA", "Planeta"),

    ]

    nome = models.CharField(max_length=100, null=False, blank=False)
    legenda = models.CharField(max_length=100, null=False, blank=False)
    categoria = models.CharField(max_length= 100,choices=OPCOES_CATEGORIA, default='')
    descricao = models.TextField(null=False, blank=False)
    foto = models.ImageField(upload_to="fotos/%Y/%m/%d/", blank=True)
    publicada = models.BooleanField(default=False)
    data_fotografia = models.DateTimeField(default=datetime.now, blank=False)


    def __str__(self):
        return  self.nome

usuarios/models.py
from django.db import models

# Create your models here.

galeria/views.py
from django.shortcuts import render,get_object_or_404
from galeria.models import Fotografia



# Create your views here.

def index(request):
    fotografias = Fotografia.objects.order_by("-data_fotografia").filter(publicada=True)
    return render(request, 'galeria/index.html', {"cards": fotografias})

def imagem(request, foto_id):
    fotografia = get_object_or_404(Fotografia, pk=foto_id)
    return render(request, 'galeria/imagem.html', {"fotografia": fotografia})

def buscar(request):
    fotografias = Fotografia.objects.order_by("-data_fotografia").filter(publicada=True)

    if "buscar" in request.GET:
        nome_a_buscar = request.GET['buscar']
        if nome_a_buscar:
            fotografias = fotografias.filter(nome__icontains=nome_a_buscar)
    return render(request, "galeria/buscar.html",{"cards": fotografias})

usuarios/views.py
from django.shortcuts import render

def login(request):
    return render(request, "usuarios/login.html")

def cadastro(request):
    return render(request, "usuarios/cadastro.html")

def buscar(request):
    return render(request, 'usuarios/buscar.html')

templates/galeria/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alura Space</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'assets/styles/style.css' %}">
</head>

<body>

    <div class="pagina">

        {% include 'galeria/partials/_header.html' %}

        <main>
            {% block content %}
            {% endblock %}
        </main>

        {% include 'galeria/partials/_footer.html' %}

    </div>

</body>

</html>

templates/galeria/buscar.html
{% extends 'galeria/base.html' %}
{% load static %}
{% block content %}

<section class="conteudo">
    <section class="banner">
        <img class="banner__imagem" src="{% static '/assets/imagens/Banner(2).png'%} " alt="banner Alura Space">
        <h1 class="banner__titulo"> A galeria mais completa de fotos do espaço!</h1>
    </section>
    <section class="tags">
        <p class="tags__titulo">Busque por tags:</p>
        <ul class="tags__lista">
            <li class="tags__tag">Nebulosa</li>
            <li class="tags__tag">Estrela</li>
            <li class="tags__tag">Galáxia</li>
            <li class="tags__tag">Planeta</li>
        </ul>
    </section>
    <section class="galeria">
        <div class="cards">
            <h2 class="cards__titulo">Navegue pela galeria</h2>
            <ul class="cards__lista">
                {% if cards %}
                {% for fotografia in cards %}
                <li class="card">
                    <a href="{% url 'galeria:imagem.html' fotografia.id %}">
                        {% if fotografia.foto == "" or fotografia.foto == null%}
                        <img class="card__imagem" src="{% static '/assets/imagens/galeria/not-found.png' %}" alt="foto">
                        {% else %}
                        <img class="card__imagem" src="{{ fotografia.foto.url}}" alt="foto">
                        {% endif %}
                    </a>
                    <span class="card__tag">Estrelas</span>
                    <div class="card__info">
                        <p class="card__titulo"> {{ fotografia.nome }}</p>
                        <div class="card__texto">
                            <p class="card__descricao">{{ fotografia.legenda }}</p>
                            <span>
                                <img src="{% static '/assets/ícones/1x/favorite_outline.png' %}" alt="ícone de coração">
                            </span>
                        </div>
                    </div>
                </li>
            </ul>
            {% endfor%}
            {% else %}
            <div class="imagem_texto">
                <p>fotografias não encontradas</p>
            </div>
            {% endif %}
        </div>
    </section>
</section>
</main>
</div>
{% endblock %}

templates/galeria/imagem.html
{% extends 'galeria/base.html' %}
{% load static %}
{% block content %}
<section class="conteudo">
    <section class="imagem">
        <div class="imagem__conteudo">
            {% if fotografia.foto == "" or fotografia.foto == null%}
            <img class="imagem__imagem" src="{% static '/assets/imagens/galeria/not-found.png ' %}">
            {% else %}
            <img class="imagem__imagem" src="{{ fotografia.foto.url }}">
            {% endif %}
            <div class="imagem__info">
                <div class="imagem__texto">
                    <p class="imagem__titulo">{{ fotografia.nome }}</p>
                    <p class="imagem__descricao">{{ fotografia.legenda }}</p>
                    <p class="imagem__texto">{{ fotografia.descricao}}</p>
                </div>
            </div>

        </div>
    </section>
</section>
{%endblock%}

templates/galeria/index.html
{% extends 'galeria/base.html' %}
{% load static %}
{% block content %}

<section class="conteudo">
    <section class="banner">
        <img class="banner__imagem" src="{% static '/assets/imagens/Banner(2).png'%} " alt="banner Alura Space">
        <h1 class="banner__titulo"> A galeria mais completa de fotos do espaço!</h1>
    </section>
    <section class="tags">
        <p class="tags__titulo">Busque por tags:</p>
        <ul class="tags__lista">
            <li class="tags__tag">Nebulosa</li>
            <li class="tags__tag">Estrela</li>
            <li class="tags__tag">Galáxia</li>
            <li class="tags__tag">Planeta</li>
        </ul>
    </section>
    <section class="galeria">
        <div class="cards">
            <h2 class="cards__titulo">Navegue pela galeria</h2>
            <ul class="cards__lista">
                {% if cards %}
                {% for fotografia in cards %}
                <li class="card">
                    <a href="{% url 'imagem.html' fotografia.id %}">
                        {% if fotografia.foto == "" or fotografia.foto == null%}
                        <img class="card__imagem" src="{% static '/assets/imagens/galeria/not-found.png' %}" alt="foto">
                        {% else %}
                        <img class="card__imagem" src="{{ fotografia.foto.url}}" alt="foto">
                        {% endif %}
                    </a>
                    <span class="card__tag">Estrelas</span>
                    <div class="card__info">
                        <p class="card__titulo"> {{ fotografia.nome }}</p>
                        <div class="card__texto">
                            <p class="card__descricao">{{ fotografia.legenda }}</p>
                            <span>
                                <img src="{% static '/assets/ícones/1x/favorite_outline.png' %}" alt="ícone de coração">
                            </span>
                        </div>
                    </div>
                </li>
            </ul>
            {% endfor%}
            {% else %}
            {% endif %}
        </div>
    </section>
</section>
</main>
</div>
{% endblock %}

templates/galeria/partials/_footer.html
{% load static %}
<footer class="rodape">
    <div class="rodape__icones">
        <a href="https://twitter.com/AluraOnline" target=”_blank”>
            <img src="{% static '/assets/icones/1x/twitter.png' %}" alt="ícone twitter">
        </a>
        <a href="https://www.instagram.com/aluraonline/" target=”_blank”>
            <img src="{% static '/assets/icones/1x/instagram.png' %}" alt="ícone instagram">
        </a>
    </div>
    <p class="rodape__texto">Desenvolvido por Alura</p>
</footer>

templates/galeria/partials/_header.html
{% load static %}
<div class="pagina-inicial">
    <header class="cabecalho">
        <img src="{% static '/assets/logo/Logo(2).png' %}" alt="Logo da Alura Space" />
        <div class="cabecalho__busca">
            <div class="busca__fundo">
                <form action="{% url 'usuarios:buscar' %}">
                    <input class="busca__input" type="text" name="buscar" placeholder="O que você procura?">
                    <button type="submit">
                        <img class="busca__icone" src="{% static '/assets/icones/1x/search.png' %}"
                            alt="ícone de search">
                    </button>
                </form>
            </div>
        </div>
    </header>
    <main class="principal">
        <section class="menu-lateral">
            <nav class="menu-lateral__navegacao">
                <a href=""><img src="{% static '/assets/icones/1x/Home - ativo.png' %}"> Home</a>
                <a href="{% url 'usuarios:login' %}"><img
                        src="{% static '/assets/icones/1x/Mais vistas - inativo.png' %}">
                    Login</a>
                <a href="{% url 'usuarios:cadastro' %}"><img src="{% static '/assets/icones/1x/Novas - inativo.png' %}">
                    Cadastro</a>
                <a href="#"><img src="{% static '/assets/icones/1x/Surpreenda-me - inativo.png' %}">
                    Surpreenda-me</a>
            </nav>
        </section>

templates/usuarios/cadastro.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alura Space</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/styles/style.css' %}">
</head>

<body>
    <div class="pagina-inicial">
        <header class="cabecalho">
            <img src="{% static '/assets/logo/Logo(2).png' %}" alt="Logo da Alura Space" />
            <div class="cabecalho__busca">
                <div class="busca__fundo">
                    <form action="{% url 'usuarios:buscar' %}">
                        <input class="busca__input" type="text" name="buscar" placeholder="O que você procura?">
                        <button type="submit">
                            <img class="busca__icone" src="{% static '/assets/ícones/1x/search.png' %}"
                                alt="ícone de search">
                        </button>
                    </form>
                </div>
            </div>
        </header>
        <main class="principal">
            <section class="menu-lateral">
                <nav class="menu-lateral__navegacao">
                    <a href="{% url 'galeria:index.html' %}"><img
                            src="{% static '/assets/ícones/1x/Home - ativo.png' %}">
                        Home</a>
                    <a href="{% url 'usuarios:login' %}"><img
                            src="{% static '/assets/ícones/1x/Mais vistas - inativo.png' %}">
                        Login</a>
                    <a href="{% url 'usuarios:cadastro' %}"><img
                            src="{% static '/assets/ícones/1x/Novas - inativo.png' %}">
                        Cadastrar</a>
                    <a href="#"><img src="{% static '/assets/ícones/1x/Surpreenda-me - inativo.png' %}"> Logout</a>
                </nav>
            </section>
            <section class="galeria" style="margin-left: 5em">
                <form action="" method="">
                    <div class="row">
                        <div class="col-12 col-lg-12" style="margin-bottom: 10px;">
                            <label for="nome_cadastro" style="color:#D9D9D9; margin-bottom: 5px;"><b>Nome
                                    completo</b></label>
                            <input type="text" class="form-control" name="nome_cadastro" placeholder="Ex.: João Silva"
                                required>
                        </div>
                        <div class="col-12 col-lg-12" style="margin-bottom: 10px;">
                            <label for="email" style="color:#D9D9D9; margin-bottom: 5px;"><b>Email</b></label>
                            <input type="email" class="form-control" name="email" placeholder="Ex.: joaosilva@xpto.com"
                                required>
                        </div>
                        <div class="col-12 col-lg-6" style="margin-bottom: 10px;">
                            <label for="password1" style="color:#D9D9D9; margin-bottom: 5px;"><b>Senha</b></label>
                            <input type="password" class="form-control" name="password1" placeholder="Digite sua senha"
                                required>
                        </div>
                        <div class="col-12 col-lg-6" style="margin-bottom: 10px;">
                            <label for="password2" style="color:#D9D9D9; margin-bottom: 5px;"><b>Confirmação de
                                    senha</b></label>
                            <input type="password" class="form-control" name="password2"
                                placeholder="Digite sua senha mais uma vez" required>
                        </div>
                        <div class="col-12 text-center">
                            <button class="btn btn-success col-12" style="padding: top 5px;" type="submit">Criar sua
                                conta</button>
                        </div>
                    </div>
                </form>
            </section>
        </main>
    </div>
</body>

{% include 'galeria/partials/_footer.html' %}

templates/usuarios/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alura Space</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>

<body>
    <div class="pagina-inicial">
        <header class="cabecalho">
            <img src="{% static 'assets/logo/Logo(2).png' %}" alt="Logo da Alura Space" />
            <div class="cabecalho_usuarios">
                <div class='busca__fundo'>
                    <form action="{% url 'usuarios:buscar' %}">
                        <input class="busca__input" type="text" name="buscar" placeholder="O que você procura?">
                        <button type="submit">
                            <img class="busca__icone" src="{% static 'assets/Ícones/1x/search.png' %}"
                                alt="ícone de search">
                        </button>
                    </form>
                </div>
            </div>
    </div>
    </header>
    <main class="principal">
        <section class="menu-lateral">
            <nav class="menu-lateral__navegacao">
                <a href="{% url 'galeria:index.html' %}"><img src="{% static 'assets/Ícones/1x/Home - ativo.png' %}">
                    Home</a>
                <a href="{% url 'usuarios:login' %}"><img
                        src="{% static 'assets/Ícones/1x/Mais vistas - inativo.png' %}">
                    Login</a>
                <a href="{% url 'usuarios:cadastro' %}"><img src="{% static 'assets/Ícones/1x/Novas - inativo.png' %}">
                    Cadastrar</a>
                <a href="#"><img src="{% static 'assets/Ícones/1x/Surpreenda-me - inativo.png' %}"> Logout</a>
            </nav>
        </section>
        <section class="galeria" style="margin-left: 5em">
            <form action="" method="">
                <div class="row">
                    <div class="col-12 col-lg-12" style="margin-bottom: 10px;">
                        <label for="nome_login" style="color:#D9D9D9; margin-bottom: 5px;"><b>Nome de
                                Login</b></label>
                        <input type="text" class="form-control" name="nome_login" placeholder="Ex.: João Silva"
                            required>
                    </div>
                    <div class="col-12 col-lg-12" style="margin-bottom: 10px;">
                        <label for="password" style="color:#D9D9D9; margin-bottom: 5px;"><b>Senha</b></label>
                        <input type="password" class="form-control" name="password" placeholder="Digite sua senha"
                            required>
                    </div>
                    <div class="col-12 text-center">
                        <button class="btn btn-success col-12" style="padding: top 5px;" type="submit">Login</button>
                    </div>
                </div>
            </form>
        </section>
    </main>
    </div>
</body>

{% include 'galeria/partials/_footer.html' %}